# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'untitled.ui'
#
# Created by: PyQt5 UI code generator 5.15.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
from PyQt5.QtCore import QSize
from PyQt5.QtGui import QMovie


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        self.setFixedSize(QSize(400, 420))
        Form.setStyleSheet("background-color: rgb(255, 255, 255)")

        #progressBar
        self.progressBar = QtWidgets.QProgressBar(Form)
        self.progressBar.setGeometry(QtCore.QRect(60, 250, 0, 0))
        self.progressBar.setProperty("value", 20)
        self.progressBar.setObjectName("progressBar")

        #gif

        self.label = QtWidgets.QLabel(Form)
        self.label.setGeometry(QtCore.QRect(80, 60, 300, 300))
        self.label.setObjectName("label")

        # set qmovie as label
        self.movie = QMovie("loading.gif")
        self.label.setMovie(self.movie)
        self.movie.start()

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Form = QtWidgets.QWidget()
    ui = Ui_Form()
    ui.setupUi(Form)
    Form.show()
    sys.exit(app.exec_())
